### ISSUE TITLE
The negative log likelihood result does not make sense

### ISSUE THREAD

**Issue by MingChiangChang** [MingChiangChang/CrystalTree.jl#4]
In the latest commit on probabilistic branch (somehow cannot put a link), the issue of Hessian being non positive semidefinite has been resolved. However, the negative log likelihood result still does not make sense. 
The term `log(dot(y, Σ⁻¹, y))` for calculating the negative log likelihood should be directly related to the residual of the optimization for that node. However, they do not match, as shown in the following figures.
<img width="606" alt="Screen Shot 2022-01-14 at 4 17 52 PM" src="https://user-images.githubusercontent.com/71734844/149586675-d59cc425-ff06-4bd9-ae2c-b2e0bbd00ecf.png">
<img width="599" alt="Screen Shot 2022-01-14 at 4 18 40 PM" src="https://user-images.githubusercontent.com/71734844/149586681-dfd737b8-05b8-4cac-85e9-c84123ca38bf.png">
The full negative log likelihood result looks like the following:
<img width="599" alt="Screen Shot 2022-01-14 at 4 22 07 PM" src="https://user-images.githubusercontent.com/71734844/149587391-8809658f-86d3-4d29-bf84-f5b50b7b284d.png">

**Comment by SebastianAment** [comment]
1) My first implementation of the marginal likelihood wasn't correct. I just fixed it [here](https://github.com/MingChiangChang/CrystalTree.jl/blob/fcb5000819a96999d13f951dad9d5b89dd6bc546/src/probabilistic.jl#L94).

2) Also, the marginal likelihood is not proportional to the residual. In principle, you can drive down the residual by adding all phases in your library, but that will actually be less likely than only adding the <4 phases that are actually present. The marginal likelihood exhibits [Occam's Razor](https://en.wikipedia.org/wiki/Occam%27s_razor) in that it will favor simpler solutions.

3) I like the third plot you generated in particular. Let's see how it looks with the correct implementation of the marginal likelihood!
